## TODO for some reason the rest client ui is not working for most of these
## TODO most of these requests need the authorization header added

###### Valid Login, this one is needed for most of the next requests, need the access token

curl -X POST http://localhost:8080/users/login \
  --data '{ "username": "crokus_younghand", "password": "phoenixinn1" }'


###### Renew access token

curl -X POST http://localhost:8080/token/renew \
  --data '{ "refreshToken": "abc" }'

###### Invalid Login - wrong password

curl -X POST http://localhost:8080/users/login \
  --data '{ "username": "crokus_younghand", "password": "phoenixinn2" }'

###### Invalid Login - user does not exist

curl -X POST http://localhost:8080/users/login \
  --data '{ "username": "crokus_lefthand", "password": "phoenixinn1" }'

###### Valid Create User 1

curl -X POST http://localhost:8080/users \
  --data '{ "username": "crokus_younghand", "fullName": "Crokus Younghand", "email": "crokus.younghand@email.com", "password": "phoenixinn1" }'

###### Valid Create User 2

curl -X POST http://localhost:8080/users \
  --data '{ "username": "crokus_oldhand", "fullName": "Crokus Oldhand", "email": "crokus.oldhand@email.com", "password": "phoenixinn1" }'

###### Valid Create User 3

curl -X POST http://localhost:8080/users \
  --data '{ "username": "michael_okeefe", "fullName": "Michael OKeefe", "email": "michael.okeefe@email.com", "password": "phoenixinn2" }'

###### Invalid Create User - short password

curl -X POST http://localhost:8080/users \
  --data '{ "username": "kruppe", "fullName": "Kruppe", "email": "kruppe@email.com", "password": "phoenix" }'

###### Valid Create Account 1
curl -X POST http://localhost:8080/accounts \
  --data '{ "owner": "crokus_younghand", "currency": "jakatas" }'

###### Valid Create Account 2
curl -X POST http://localhost:8080/accounts \
  --data '{ "owner": "crokus_oldhand", "currency": "jakatas" }'

###### Valid Create Account 3
curl -X POST http://localhost:8080/accounts \
  --data '{ "owner": "michael_okeefe", "currency": "usd" }'

###### Invalid Create Account - invalid currency
curl -X POST http://localhost:8080/accounts \
--data '{ "owner": "crokus_younghand", "currency": "EUR" }'

###### Invalid Create Account - missing owner
curl -X POST http://localhost:8080/accounts \
--data '{ "owner": "", "currency": "jakatas" }'

###### Valid Get Account
###### Sub account id with an id from previous Valid Create request
curl "http://localhost:8080/accounts/5c8b2ef6-1b04-4486-9c6a-aba1e791e343"


###### Not found get
curl "http://localhost:8080/accounts/5c8b2ef6-1b04-4486-9c6a-aba1e791e342"


###### Invalid List Accounts - No pagination data
curl "http://localhost:8080/accounts"

###### Valid List Accounts - page 1
curl -H "Authorization: Bearer <access_token>" "http://localhost:8080/accounts?page=1&pageSize=10"

###### Valid List Accounts - empty page
curl "http://localhost:8080/accounts?page=10000&pageSize=10"


###### Valid Create Transfer
## NOTE this will required two accounts first - crokus younghand and crokus oldhand
curl -X POST http://localhost:8080/transfers \
  --data '{ "fromAccountId": "3acec005-c175-454a-a41d-216eb33f000c", "toAccountId": "81e402b7-ba1c-42e8-8a5a-95625a8be919", "amount": 100, "currency": "jakatas" }'

###### Invalid Create Transfer - currency mismatch
## NOTE this will required two accounts first - crokus younghand and michael okeefe
curl -X POST http://localhost:8080/transfers \
  --data '{ "fromAccountId": "3acec005-c175-454a-a41d-216eb33f000c", "toAccountId": "2ba06319-594d-4dce-a9db-a45ec23344fb", "amount": 100, "currency": "jakatas" }'

###### Invalid Create Transfer - invalid currency
## NOTE this will required two accounts first - crokus younghand and michael okeefe
curl -X POST http://localhost:8080/transfers \
  --data '{ "fromAccountId": "3acec005-c175-454a-a41d-216eb33f000c", "toAccountId": "2ba06319-594d-4dce-a9db-a45ec23344fb", "amount": 100, "currency": "eur" }'
