version: '3'

services:
  #  start Postgres, and ensure that data is stored to a mounted volume
  go-remix-postgres:
    image: 'postgres:13.4'
    ports:
      - '5433:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: celeritas
    volumes:
      - ./_db-data/postgres/:/var/lib/postgresql/data/

  #  start Redis, and ensure that data is stored to a mounted volume
  go-remix-redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - ./_db-data/redis/:/data

  #  start MariaDB, and ensure that data is stored to a mounted volume
  go-remix-mariadb:
    image: 'mariadb:10.6'
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: celeritas
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: password

    volumes:
      - ./_db-data/mariadb:/docker-entrypoint-initdb.d
