FROM golang:1.19-alpine
RUN apk add --no-cache make
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

WORKDIR /migrate
COPY . .

RUN mv -f .env.docker .env

# TODO this command gets output in docker logs. not good! because password logged
CMD ["make",  "migratedb"]
