// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id uuid.UUID) error
	GetAccount(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountForUpdate(ctx context.Context, id uuid.UUID) (Account, error)
	GetEntry(ctx context.Context, id uuid.UUID) (Entry, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTransfer(ctx context.Context, id uuid.UUID) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	// NO KEY UPDATE tells pg that the PK column won't be changing
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	// Option one with flags and case statement
	// UPDATE users
	// SET
	//   hashed_password = CASE
	//     WHEN @set_hashed_password::boolean = TRUE THEN @hashed_password::text
	//     ELSE hashed_password
	//   END,
	//   full_name = CASE
	//     WHEN @set_full_name::boolean = TRUE THEN @full_name::text
	//     ELSE full_name
	//   END,
	//   email = CASE
	//     WHEN @set_email::boolean = TRUE THEN @email::text
	//     ELSE email
	//   END
	// WHERE
	//   username = @username::text
	// RETURNING *;
	// Better option using nullable fields with coalesce
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
