name: simple-bank-ci-test

on:
  pull_request:
    branches: ["main"]
    paths: ["simple-bank/**"]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    # Opting to use docker-compose directly
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: simple-bank
          POSTGRES_USER: simple-bank-user
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Env
        working-directory: ./simple-bank
        run: touch .env && echo ${{ secrets.SIMPLE_BANK_ENV }} > .env

      # - name: Set up services
      #   working-directory: ./simple-bank
      #   run: docker-compose up -d

      - name: Install migrate
        working-directory: ./simple-bank
        run: |
          $ curl -L https://github.com/golang-migrate/migrate/releases/download/$version/migrate.$platform-amd64.tar.gz | tar xvz

      - name: Migrate
        working-directory: ./simple-bank
        run: migrate -path db/migrations -database "postgresql://simple-bank-user:${{secrets.POSTGRES_PASSWORD}}@localhost:5432/simple-bank?sslmode=disable" -verbose up

      - name: Test
        working-directory: ./simple-bank
        run: make test
