name: simple-bank-ci-test

on:
  # push:
  #   branches: [ "main" ]
  #   paths: [ "simple-bank" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "simple-bank/**" ]

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    # Build will happen automatically when running test
    # - name: Build
    #   run: go build -v ./...

    - name: Test
      run: make test
